name='jigsaw3D'

def flipL(list):
	out=[]
	flip={}
	flip['l']=['i']
	flip['i']=['r']
	flip['r']=['o']
	flip['o']=['l']
	flip['u']=['u']
	flip['d']=['d']

	flip['L']=['I']
	flip['I']=['C']
	flip['C']=['O']
	flip['O']=['L']

	flip['R']=['G']
	flip['G']=['B']
	flip['B']=['F']
	flip['F']=['R']

	flip['W']=['T']
	flip['T']=['J']
	flip['J']=['P']
	flip['P']=['W']

	flip['H']=['M']
	flip['M']=['E']
	flip['E']=['Q']
	flip['Q']=['H']

	flip['U']=['V']
	flip['V']=['X']
	flip['X']=['N']
	flip['N']=['U']

	flip['D']=['Y']
	flip['Y']=['Z']
	flip['Z']=['S']
	flip['S']=['D']

	for item in list:
		out.extend(flip[item])
	return out

def flipR(list):
	out=flipL(flipL(flipL(list)))
	return out

def reverse(originalList):
	list=originalList[:]
	out=[]
	rev={}

	rev['l']=['r']
	rev['r']=['l']

	rev['i']=['o']
	rev['o']=['i']

	rev['u']=['d']
	rev['d']=['u']

	rev['B']=['C']
	rev['C']=['B']

	rev['D']=['U']
	rev['U']=['D']

	rev['E']=['W']
	rev['W']=['E']

	rev['F']=['O']
	rev['O']=['F']

	rev['G']=['I']
	rev['I']=['G']

	rev['H']=['J']
	rev['J']=['H']

	rev['X']=['Z']
	rev['Z']=['X']

	rev['L']=['R']
	rev['R']=['L']

	rev['M']=['P']
	rev['P']=['M']

	rev['N']=['S']
	rev['S']=['N']

	rev['Q']=['T']
	rev['T']=['Q']

	rev['V']=['Y']
	rev['Y']=['V']

	list.reverse()
	for item in list:
		out.extend(rev[item])
	return out

def flipx(list):
	out=[]
	flip={}
	flip['l']=['r']
	flip['r']=['l']
	flip['i']=['i']
	flip['o']=['o']
	flip['u']=['u']
	flip['d']=['d']

	flip['L']=['R']
	flip['R']=['L']
	flip['B']=['C']
	flip['C']=['B']
	flip['I']=['F']
	flip['F']=['I']
	flip['G']=['O']
	flip['O']=['G']

	flip['W']=['E']
	flip['E']=['W']
	flip['H']=['J']
	flip['J']=['H']
	flip['P']=['Q']
	flip['Q']=['P']
	flip['M']=['T']
	flip['T']=['M']

	flip['U']=['N']
	flip['N']=['U']
	flip['V']=['X']
	flip['X']=['V']

	flip['D']=['S']
	flip['S']=['D']
	flip['Y']=['Z']
	flip['Z']=['Y']

	for item in list:
		out.extend(flip[item])
	return out

def flipz(list):
	out=flipL(flipL(flipx(list)))
	return out

def flipU(list):
	out=[]
	flip={}

	flip['l']=['l']
	flip['r']=['r']
	flip['o']=['u']
	flip['u']=['i']
	flip['i']=['d']
	flip['d']=['o']

	flip['B']=['H']
	flip['H']=['W']
	flip['W']=['L']
	flip['L']=['B']

	flip['C']=['J']
	flip['J']=['E']
	flip['E']=['R']
	flip['R']=['C']

	flip['G']=['V']
	flip['V']=['T']
	flip['T']=['D']
	flip['D']=['G']

	flip['I']=['Y']
	flip['Y']=['Q']
	flip['Q']=['U']
	flip['U']=['I']

	flip['F']=['Z']
	flip['Z']=['P']
	flip['P']=['N']
	flip['N']=['F']

	flip['O']=['X']
	flip['X']=['M']
	flip['M']=['S']
	flip['S']=['O']

	for item in list:
		out.extend(flip[item])
	return out

def flipD(list):
	out=flipU(flipU(flipU(list)))
	return out

def flipP(list):
	out=flipR(flipU(flipL(list)))
	return out


#alphabet rules
alphabet={}

alphabet['o']=['o']
alphabet['i']=['i']
alphabet['r']=['r']
alphabet['d']=['d']
alphabet['u']=['u']
alphabet['l']=['l']

#group I - front
alphabet['R']=list('rrrrdlllldrrorirrdllolilldrrrrrdlllllirrrrrulllllurrrrrulllllurrrrullllidrururdrdrdrdlddlulurululdldrdldluidrurulururdrdldrdruurululululdldluidddddruuuuurdddddruuuuurdddddruuuuiddddluuuullldddrrdllluuuuurrrrroooodou')
alphabet['L']=reverse(alphabet['R'])

alphabet['O']=flipL(flipU(alphabet['R']))
alphabet['F']=reverse(alphabet['O'])

alphabet['N']=flipD(flipR(alphabet['R']))
alphabet['S']=reverse(alphabet['N'])

#group II - side
alphabet['D']=list('rrrrrdllllldrrorirrdllolilldrrrrrdlllliuuuuurdddddruuuuurdddddruuuuuiiiillllldddddrrrulluuurrrddddruuuuoddddluuuuuldddddluuuuuldddddluuuuuodrururdrdrdrdlddlulurululdldrdldluodrurulururdrdldrdruurululululdldluodddddo')
alphabet['U']=reverse(alphabet['D'])

alphabet['M']=flipD(flipR(alphabet['D']))
alphabet['P']=reverse(alphabet['M'])

alphabet['B']=flipL(flipU(alphabet['D']))
alphabet['C']=reverse(alphabet['B'])

alphabet['I']=flipz(flipU(alphabet['D']))
alphabet['G']=reverse(alphabet['I'])

alphabet['Z']=flipx(flipL(alphabet['D']))
alphabet['X']=reverse(alphabet['Z'])

alphabet['W']=flipx(flipP(alphabet['D']))
alphabet['E']=reverse(alphabet['W'])

#group III - back
alphabet['T']=list('uuuuurdddddruuouiuurddodiddruuuuurdddddilllllurrrrrulllllurrrrrulllllirururdrdrdrdlddlulurululdldrdldluidrurulururdrdldrdruurululululdldluoorrrrriiidddddluuuuuldddddluuuuuldddddluuuuuirrrrrdddddllllurrruuulllldrdldd')
alphabet['Q']=reverse(alphabet['T'])

alphabet['H']=flipx(flipL(alphabet['T']))
alphabet['J']=reverse(alphabet['H'])

alphabet['Y']=flipD(flipz(alphabet['T']))
alphabet['V']=reverse(alphabet['Y'])


##rewrite rules
#generated by randsolve in checker

rewrite={}

rewrite['o']=['o']
rewrite['i']=['i']
rewrite['r']=['r']
rewrite['d']=['d']
rewrite['u']=['u']
rewrite['l']=['l']

#group I - front
rewrite['R']=list('RrRrRrRrDdIlBlBlBlZdOrRrRoZrViRrRrDdIlBlOoBlZiWlWlMdOrRrRrRrRrDdDlWlWlWlWlMiNrRrRrRrRrRuWlWlWlWlWlNuNrRrRrRrRrIuQlWlWlWlWlNuNrRrRrRrRuWlWlWlWlMiMdZrVuJrVuJrJdZrJdOrDdRrDdDlMdZdBlBuVlOuMrVuQlNuWlWdDlWdRrDdIlZdBlBuViDdRrIuJrVuQlNuMrVuJrJdZrJdBlZdOrDdRrRuNuMrVuQlNuWlNuWlNuWlWdIlZdBlBuViDdDdDdDdDdRrIuVuVuVuVuJrQdDdDdDdDdRrRuNuNuNuNuNrDdDdDdDdDdRrRuNuNuNuMiMdZdZdZdBlOuNuNuNuWlWlWlMdZdZdOrRrDdDlWlWlNuNuNuNuNuNrRrRrRrRrRoOoOoOoZdOoOuN')
rewrite['L']=reverse(rewrite['R'])

rewrite['O']=flipL(flipU(rewrite['R']))
rewrite['F']=reverse(rewrite['O'])

rewrite['N']=flipD(flipR(rewrite['R']))
rewrite['S']=reverse(rewrite['N'])

#group II - side
rewrite['D']=list('RrRrRrRrRrDdIlBlBlBlBlZdZrJrQoJrJiMrJrJdBlBlOoBlZiWlWlMdOrRrRrRrRrDdDlWlWlWlMiNuNuNuNuNuNrDdDdDdDdDdRrIuVuVuVuVuJrQdDdDdDdDdRrIuVuVuVuVuJiMiMiMiWlWlWlWlWlWdDdDdDdDdRrRrRrRuWlWlNuNuNuNrRrRrDdDdDdDdRrIuVuVuVuQoQdDdDdDdIlBuVuVuVuVuVlZdZdZdZdZdBlBuVuVuVuVuQlWdDdDdDdDdDlNuNuNuNuNuWoQdRrRuMrVuJrJdZrJdZrQdRrDdDlWdDdDlNuWlNuNrIuVlBuVlZdBlZdZrQdIlZdBlBuQoQdRrIuJrVuQlNuMrVuJrQdRrDdIlZdOrDdRrRuNuMrVuQlNuWlNuWlNuWlMdBlZdBlOuWoQdDdDdDdDdDoQ')
rewrite['U']=reverse(rewrite['D'])

rewrite['M']=flipD(flipR(rewrite['D']))
rewrite['P']=reverse(rewrite['M'])

rewrite['B']=flipL(flipU(rewrite['D']))
rewrite['C']=reverse(rewrite['B'])

rewrite['I']=flipz(flipU(rewrite['D']))
rewrite['G']=reverse(rewrite['I'])

rewrite['Z']=flipx(flipL(rewrite['D']))
rewrite['X']=reverse(rewrite['Z'])

rewrite['W']=flipx(flipP(rewrite['D']))
rewrite['E']=reverse(rewrite['W'])

#group III - back
rewrite['T']=list('UuUuUuUuUuErTdYdYdYdYdCrCuXuPoXuHiUuUuErTdYdGoYdYiTdYdCrCuXuXuXuXuXrYdYdYdYdYdCiLlLlLlLlLlLuErErErErErUuTlHlHlHlHlXuXrCrCrCrCrCuHlHlHlHlHlXiSrUuErUuErTdCrYdCrYdCrYdGlSdSdLlLuTlXuPrUuTlXuHlPdLlSdFrYdGlSdLlLuTiTdCrCuXrCuHlXuXrCuXrYdCrYdYlHdCrYdCrGuUuErUuTlXuHlXuHlXuHlHdGlSdLlFuPoPoXrCrCrCrCrYiTiTiEdSdSdSdSdLlLuUuUuUuUuUlSdSdSdSdSdLlFuXuXuXuXuHlHdYdYdYdYdYlXuXuXuXuXuXiSrErErErErEdSdSdSdSdLlLlLlLlFuXrCrCrCuXuXuHlHlHlHlHdCrYdYlHdYdY')
rewrite['Q']=reverse(rewrite['T'])

rewrite['H']=flipx(flipL(rewrite['T']))
rewrite['J']=reverse(rewrite['H'])

rewrite['Y']=flipD(flipz(rewrite['T']))
rewrite['V']=reverse(rewrite['Y'])




symbols='R'












## by group

group={}
group['o']='basic'
group['i']='basic'
group['r']='basic'
group['d']='basic'
group['u']='basic'
group['l']='basic'

group['R']='I'
group['L']='I'
group['O']='I'
group['F']='I'
group['N']='I'
group['S']='I'

group['D']='II'
group['U']='II'
group['M']='II'
group['P']='II'
group['B']='II'
group['C']='II'
group['I']='II'
group['G']='II'
group['Z']='II'
group['X']='II'
group['W']='II'
group['E']='II'

group['T']='III'
group['Q']='III'
group['H']='III'
group['J']='III'
group['Y']='III'
group['V']='III'
